// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qoscthipdywqoeftozij.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFvc2N0aGlwZHl3cW9lZnRvemlqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5ODA5MDQsImV4cCI6MjA1ODU1NjkwNH0.wRu_RhGNzCdx6u7El7MvUFqV59r7KyW2mlgqTzCFi1s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);